# Generated by Django 3.2.9 on 2021-11-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='homework',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
