# Generated by Django 3.2.9 on 2021-11-16 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0002_auto_20211116_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapi.student'),
        ),
    ]
