# Generated by Django 3.2.9 on 2021-11-22 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0003_alter_exam_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapi.student'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapi.student'),
        ),
    ]
